fit:
  model:
    class_path: models.LitUnet3D
    init_args:
      in_channels: 1
      out_channels: 1
      n_levels: 3
      n_features_root: 32
      lr: .0001

  data:
    class_path: data.CnfCombustionDataModule
    init_args:
      batch_size: 1
      num_workers: 0
      splitting_lengths: [111, 8, 8]
      subblock_shape: [32, 16, 16]  # keeping power 2 dimensions for the U-net.

  trainer:
    max_epochs: 10
    accelerator: "cpu"
    devices:
      - 0
