fit:
  model:
    class_path: models.LitUnet3D
    init_args:
      in_channels: 1
      out_channels: 1
      n_levels: 5
      n_features_root: 32
      lr: .0001

  data:
    class_path: data.CnfCombustionDataModule
    init_args:
      batch_size: 1
      num_workers: 0

  trainer:
    max_epochs: 1000
    accelerator: "cpu"
    devices:
      - 0
