[mypy]

mypy_path = weather-forecast/nwp-emulation/panguweather

# Override mypy default value `ignore_missing_imports = false` to `true` for modules with no typing
# Has the effect of silencing `import-untyped` error
[mypy-zarr]
ignore_missing_imports = true