[mypy]

mypy_path = reactive-flows/cnf-combustion/unets

# Override mypy default value `ignore_missing_imports = false` to `true` for modules with no typing
# Has the effect of silencing `import-untyped` error
[mypy-h5py]
ignore_missing_imports = true
