fit:
    model:
        class_path: models.LitGAT
        init_args:
            in_channels: 1
            hidden_channels: 32
            out_channels: 1
            num_layers: 4
            dropout: .5
            heads: 8
            jk: "last"
            lr: .0001

    data:
        class_path: data.LitCombustionDataModule
        init_args:
            batch_size: 1
            num_workers: 0

    trainer:
        max_epochs: 1000
        accelerator: "cpu"
        devices:
            - 0