fit:
    model:
        class_path: models.LitGCN
        init_args:
            in_channels: 1
            hidden_channels: 32
            out_channels: 1
            num_layers: 4
            dropout: .5
            jk: "last"
            lr: .0001

    data:
        class_path: data.LitCombustionDataModule
        init_args:
            batch_size: 1
            num_workers: 0
    
    trainer:
        max_epochs: 1000
        accelerator: "gpu"
        devices: 
            - 0