fit:
    model:
        class_path: models.LitGraphUNet
        init_args:
            in_channels: 1
            hidden_channels: 32
            out_channels: 1
            depth: 4
            pool_ratios: .5
            lr: .0001

    data:
        class_path: data.LitCombustionDataModule
        init_args:
            batch_size: 1
            num_workers: 0
    
    trainer:
        max_epochs: 1000
        accelerator: "gpu"
        devices: 
            - 0