fit:
    model:
        class_path: models.LitUnet1D
        init_args:
            in_channels: 47
            out_channels: 4
            n_levels: 3
            n_features_root: 32
            norm: True
            flux_loss_weight: 1000
            hr_loss_weight: 10000

    optimizer:
        class_path: torch.optim.AdamW
        init_args:
            lr: .0001
    
    lr_scheduler:
        class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
        init_args:
            T_0 : 20
            T_mult : 2

    data:
        class_path: data.LitThreeDCorrectionDataModule
        init_args:
            timestep: 3500
            patchstep: 16
            batch_size: 32
            num_workers: 4
            splitting_lengths:
                - .8
                - .1
                - .1

    trainer:
        callbacks:
            - class_path: pytorch_lightning.callbacks.ModelCheckpoint
              init_args:
                  monitor: val_loss
                  mode: min
                  save_top_k: 1
                  every_n_epochs: 1
                  auto_insert_metric_name : false
            - class_path: pytorch_lightning.callbacks.LearningRateMonitor
              init_args:
                  logging_interval: epoch
        max_epochs: 10
        accelerator: gpu
        strategy: ddp_find_unused_parameters_false
        devices:
            - 1
