fit:
    model:
        class_path: models.LitUnet1D
        init_args:
            data_path: /root/bovaloc/ai4sim-github/model-collection/weather_forecast/3dcorrection/unets/data/processed
            in_channels: 47
            out_channels: 4
            n_levels: 3
            n_features_root: 32
            lr: .0001
            norm: True
            flux_loss_weight: 1000
            hr_loss_weight: 10000

    data:
        class_path: data.LitThreeDCorrectionDataModule
        init_args:
            data_path: ${fit.model.init_args.data_path}
            timestep: 3500
            patchstep: 16
            batch_size: 32
            num_workers: 4
            splitting_lengths:
                - .8
                - .1
                - .1

    trainer:
        max_epochs: 10
        accelerator: "gpu"
        strategy: "ddp"
        devices:
            - 1
