# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

seed_everything: 0

model:
    class_path: models.LitGraphUNet
    init_args:
        in_channels: 1
        hidden_channels: 32
        out_channels: 1
        depth: 4
        pool_ratios: .5
        lr: .0001

data:
    class_path: data.R2DataModule
    init_args:
        batch_size: 1
        num_workers: 0
        y_normalizer: 3295.4
        splitting_ratios: [0.8, 0.1, 0.1]
        data_path: ${oc.decode:${oc.env:DATADIR, ./data}}

trainer:
    max_epochs: 1
    accelerator: "cpu"
    devices: ${oc.decode:${oc.env:SLURM_GPUS_ON_NODE, 1}}
    logger:
        class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
        init_args:
            save_dir: ${oc.decode:${oc.env:LOGDIR, ./logs}}