[mypy]

mypy_path = reactive-flows/cnf-combustion/gnns

# Override mypy default value `ignore_missing_imports = false` to `true` for modules with no typing
# Has the effect of silencing `import-untyped` error
[mypy-h5py]
ignore_missing_imports = true
[mypy-networkx]
ignore_missing_imports = true
[mypy-torch_geometric]
ignore_missing_imports = true
[mypy-plotly]
ignore_missing_imports = true
[mypy-plotly.graph_objects]
ignore_missing_imports = true
[mypy-plotly.subplots]
ignore_missing_imports = true