fit:
    model:
        class_path: models.LitGAT
        init_args:
            in_channels: 21
            hidden_channels: 8
            out_channels: 6
            num_layers: 4
            dropout: .3
            edge_dim: 27
            heads: 8
            jk: "last"
            lr: .0001
            timestep: 3500
            norm: True

    data:
        class_path: data.LitThreeDCorrectionDataModule
        init_args:
            timestep: 3500
            patchstep: 16
            batch_size: 64
            num_workers: 0
    
    trainer:
        max_epochs: 1
        accelerator: "gpu"
        devices: 
            - 0