model:
    class_path: models.LitMeta
    init_args:
        edge_in_feat: 50
        edge_out_feat: 2
        edge_hidden: 64
        node_in_feat: 5
        node_out_feat: 4
        node_hiddens: 
            - 16
            - 32
            - 52
            - 16
        global_in_feat: 21
        global_out_feat: 4
        global_hidden: 64
        lr: 0.01
        sw_weight: 1.e2
        lw_weight: 1.e1
        hr_sw_weight: 1.e3
        hr_lw_weight: 1.e3

data:
    class_path: data.LitThreeDCorrectionDataModule
    init_args:
        timestep: 3501
        patchstep: 16
        date: '20200101'
        subset: None
        norm: True
        batch_size: 128
        num_workers: 8
        prefetch_factor: 4

trainer:
    max_epochs: 100
    accelerator: "gpu"
    strategy: auto
    devices:
        - 1
    mlflow_setup:
        tracking:
            uri: http://172.16.118.155:5000
            experiment_name: gnn_ecrad
            model_name: gnn_ecrad_model
        git:
            git_python_refresh: quiet