fit:
    model:
        class_path: models.LitUnet1D
        init_args:
            in_channels: 47
            out_channels: 6
            n_levels: 3
            n_features_root: 32
            lr: .0001

    data:
        class_path: data.LitThreeDCorrectionDataModule
        init_args:
            timestep: 1000
            patchstep: 1
            batch_size: 256
            num_workers: 0

    trainer:
        max_epochs: 50
        accelerator: "cpu"
        devices:
            - 0