[mypy]

mypy_path = weather-forecast/ecrad-3d-correction/unets

# Override mypy default value `ignore_missing_imports = false` to `true` for modules with no typing
# Has the effect of silencing `import-untyped` error
[mypy-h5py]
ignore_missing_imports = true
[mypy-climetlab]
ignore_missing_imports = true