name: ai4sim-ci-cd

on: [push]

jobs:
  ai4sim-ci-cd:
    runs-on: nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
