name: ai4sim-ci-cd

on: [push, pull_request]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        test-path: 
#          - combustion/gnns/
#          - combustion/unets/
          - weather_forecast/gwd/
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: excitedleigh/setup-nox@v2.0.0
    - name: Analysing the code with flake8
      working-directory: ${{ matrix.test-path }}
      run: nox -s lint
    - name: Run unit tests with coverage report
      working-directory: ${{ matrix.test-path }}
      run: nox -s tests
    - name: Coverage Commentator
      uses: 5monkeys/cobertura-action@master
      with:
        path: ${{ matrix.test-path }}.ci-reports/pycoverage.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 80
        show_missing: true
        link_missing_lines: true
        link_missing_lines_source_dir: ${{ matrix.test-path }}

