name: ai4sim-ci-cd

on: [push, pull_request]

jobs:
  run-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        use-case:
          - combustion/gnns
          - combustion/unets
          - weather_forecast/gravity-wave-drag/cnns
          - weather_forecast/ecrad-3d-correction/unets
      fail-fast: false

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Read use-case env.yaml file
      uses: pietrobolcato/action-read-yaml@1.1.0
      id: uc_env
      with:
        config: ${{ matrix.use-case }}/env.yaml

    - name: Set up Python ${{ steps.uc_env.outputs['python_version'] }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.uc_env.outputs['python_version'] }}

    - name: Install nox build tool
      run: pip3 install $(grep nox== ${{ matrix.use-case }}/requirements.txt)

    - name: Analysing the code with flake8
      working-directory: ${{ matrix.use-case }}
      run: nox -s lint -v

    - name: Run unit tests with coverage report
      working-directory: ${{ matrix.use-case }}
      run: nox -s tests -v

    - name: Coverage Commentator
      uses: 5monkeys/cobertura-action@master
      with:
        path: ${{ matrix.use-case }}/.ci-reports/pycoverage.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 0
        fail_below_threshold: false
        show_missing: true
        link_missing_lines: true
        link_missing_lines_source_dir: ${{ matrix.use-case }}
        report_name: Coverage report for ${{ matrix.use-case }} use-case
