name: auto-merge-to-public

on:
  workflow_run:
    workflows: [ai4sim-ci-cd]
    branches: [private/main]
    types: [completed]

permissions:
  actions: write
  contents: write
  checks: read
  pull-requests: write

jobs:
  auto-merge-to-public:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    steps:
        - name: echo
          run: echo "success"
