name: auto-pr-to-public

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  auto-pr-to-public:
    runs-on: ubuntu-latest

    if: github.event.repository.name == 'model-collection-private'

    steps:

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.AI4SIM_APP_ID }}
          private-key: ${{ secrets.AI4SIM_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout public sources
        uses: actions/checkout@v6
        with:
          repository: AI4SIM/model-collection
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Create branch to be commited
        run: |
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/AI4SIM/model-collection.git
          git remote add private https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/AI4SIM/model-collection-private.git
          git fetch private main:${{ vars.MODEL_COLLECTION_BRANCH_NAME }}
          git push origin ${{ vars.MODEL_COLLECTION_BRANCH_NAME }}

      - name: Create the PR on public side
        run: gh pr create -H '${{ vars.MODEL_COLLECTION_BRANCH_NAME }}' --title 'Merge private into public' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}