name: pylint-wkfl.yml

on: [push]

jobs:
  install-run-pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install requirements
      run: |
        if [ -f combustion/gnns/requirements.txt ]; then
          python -m pip install -r combustion/gnns/requirements.txt
        fi
#     - name: Analysing the code with pylint
      # run: |
      #   pylint 'combustion/gnns/test.py'
